insert into author (name, birth_date, particularity)
values ('Ashlin Chidlow', '1989-05-03',
        'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices'),
       ('Julianne Zamudio', '1996-09-05', 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu'),
       ('Cornelia Conws', '1993-09-10',
        'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque'),
       ('Orson Sappell', '1998-06-09',
        'ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer'),
       ('Kit Kensley', '1991-12-26', 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum'),
       ('Dare Mallall', '1996-06-16',
        'praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante'),
       ('Hector Voas', '1989-11-27', 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at'),
       ('Hilton Hourihan', '1988-07-31',
        'quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc'),
       ('Ellwood Vakhlov', '1985-05-28',
        'quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu'),
       ('Jeffy Lardez', '1985-12-29',
        'urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate'),
       ('Mariann Jopson', '1990-07-01', 'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget'),
       ('Di Dongall', '1995-03-05',
        'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor'),
       ('Jayme Warlaw', '1991-12-26', 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id'),
       ('Madalena Shakeshaft', '1986-07-08',
        'quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum'),
       ('Lucy O''Shea', '1987-02-07', 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit'),
       ('Rozele Bartolozzi', '2000-04-26',
        'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa'),
       ('Lottie Palk', '1987-04-15', 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet'),
       ('Goldy Rallings', '1985-09-29',
        'aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed'),
       ('Hart Frith', '1992-08-22',
        'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate'),
       ('Meier Palmer', '1986-05-06', 'sapien sapien non mi integer ac neque duis bibendum morbi');
